config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'bill#show'

  get '/pdf', to: 'bill#pdf', as: 'bill_pdf'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill
  END_POINT = 'http://safe-plains-5453.herokuapp.com/bill.json'

  def self.latest
    json = API.get(END_POINT)

    return if json.blank?

    Bill.new(json)
  end

  def initialize(source)
    @source = underscore_keys(source)
  end

  def method_missing(*args)
    @source.send(*args)
  end

  private

  def underscore_keys(value)
    case value
    when Array
      value.map(&method(:underscore_keys))
    when Hash
      Hash[value.map { |k, v| [underscore_key(k), underscore_keys(v)] }]
    else
      value
    end
  end

  def underscore_key(key)
    key.to_s.underscore.to_sym
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bill_controller.rb
class BillController < ApplicationController
  helper_method :bill

  def show
  end

  def pdf
    send_data BillPDF.new(bill).render, type: 'application/pdf', filename: 'my_bill.pdf'
  end

  private

  def bill
    @bill ||= Bill.latest
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bill_helper.rb
module BillHelper
  def bill_period(place=:from)
    date_string(bill[:statement][:period][place])
  end

  def currency(number)
    number_to_currency(number, unit: '£')
  end

  def date_string(string)
    Date.parse(string).strftime('%d %b')
  end

  def rental_charge_total
    bill[:sky_store][:rentals].sum { |rental| rental[:cost] }
  end
end

app/views/bill/_bill_section.html.haml
%button.dropdown{id: id, 'aria-expanded' => 'false', data: {toggle: 'collapse', target: "##{target}"} }
  %h4
    = content_for(:button_title)
    .pull-right
      %span.overview.text-muted= content_for(:dropdown_amount)
      %a.glyphicon.glyphicon-chevron-down
      %a.glyphicon.glyphicon-chevron-left

.collapse{ id: target}
  = yield

app/views/bill/_phone_charges.html.haml
- content_for(:button_title, flush: true) do
  Phone usage
  %small.overview Calls charged outside included service

- content_for(:dropdown_amount, flush: true) do
  = currency(bill[:call_charges][:total])

= render 'bill_section', id: 'phone_charges', target: 'phone_expanded' do
  %table.table.phone_charges
    %caption Calls charged outside included service
    %tr
      %th.col-sm-4 Recipient
      %th.col-sm-5 Duration
      %th.col-sm-3 Charge
    - bill[:call_charges][:calls].each do |call_details|
      %tr
        %td.col-sm-4= call_details[:called]
        %td.col-sm-5= call_details[:duration]
        %td.col-sm-3= currency(call_details[:cost])
    %tr
      %td
      %td
      %td
        %b #{currency(bill[:call_charges][:total])}

app/views/bill/_subscriptions.html.haml
- content_for(:button_title, flush: true) do
  Subscriptions
  %small #{bill_period(:from)} - #{bill_period(:to)}

- content_for(:dropdown_amount, flush: true) do
  = currency(bill[:package][:total])

= render 'bill_section', id: 'subscription', target: 'subscriptions_expanded' do
  %table.table.subscriptions
    %caption This bill covers next months basic subscriptions
    - bill[:package][:subscriptions].each do |subscription|
      %tr
        %td.col-sm-3= subscription[:name]
        %td.col-sm-9
          .pull-right= currency(subscription[:cost])
    %tr
      %td
        %td
          %b.pull-right Subtotal #{currency(bill[:package][:total])}

app/views/bill/_tv_charges.html.haml
- content_for(:button_title, flush: true) do
  Sky TV Store
  %small.overview Rentals &amp; Purchases

- content_for(:dropdown_amount, flush: true) do
  = currency(rental_charge_total)

= render 'bill_section', id: 'tv_charges', target: 'tv_expanded' do
  %table.table.tv_charges
    %tr
      %th.col-sm-5 Title
      %th.col-sm-4
      %th.col-sm-3 Charge
    %caption Rentals &amp; Purchases
    - bill[:sky_store][:rentals].each do |rental|
      %tr
        %td.col-sm-5= rental[:title]
        %td.col-sm-4 Rental
        %td.col-sm-3= currency(rental[:cost])
    - bill[:sky_store][:buy_and_keep].each do |purchase|
      %tr
        %td.col-sm-5= purchase[:title]
        %td.col-sm-4 Purchase
        %td.col-sm-3.text-muted £0.00 (#{currency(purchase[:cost])} paid)
    %tr
      %td
      %td
      %td
        %b= currency(rental_charge_total)

app/views/bill/show.html.haml
.col-sm-12
  - if bill.blank?
    - content_for :alert do
      .alert.alert-danger
        An error occurred whilst fetching your bill, please refresh the page to try again.
  - else
    %h3
      Latest Bill
      %small Due #{date_string(bill[:statement][:due])}
      %span.pull-right= currency(bill[:total])
    %hr

      = render 'subscriptions'
      %hr
      = render 'phone_charges'
      %hr
      = render 'tv_charges'
      %hr

      .pull-right
        = link_to bill_pdf_path, target: '_blank', class: 'btn' do
          %i.glyphicon.glyphicon-download
          %span Download PDF

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{ name: "viewport", content: "initial-scale=1.0, width=device-width" }
    %title SkyBill
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      .header
        %ul.nav.nav-pills.pull-right
          %li.active
            %a Billing
          %li
            %a Other
        %h3.text-muted SkyBilling
      = content_for :alert
      = yield

app/views/pages/_phone_charges.html.haml
- content_for(:button_title, flush: true) do
  Phone usage
  %small.overview Calls charged outside included service

- content_for(:dropdown_amount, flush: true) do
  = currency(resource[:call_charges][:total])

= render 'bill_section', id: 'phone_charges', target: 'phone_expanded' do
  %table.table.phone_charges
    %caption Calls charged outside included service
    %tr
      %th.col-sm-4 Recipient
      %th.col-sm-5 Duration
      %th.col-sm-3 Charge
    - resource[:call_charges][:calls].each do |call_details|
      %tr
        %td.col-sm-4= call_details[:called]
        %td.col-sm-5= call_details[:duration]
        %td.col-sm-3= currency(call_details[:cost])
    %tr
      %td
      %td
      %td
        %b #{currency(resource[:call_charges][:total])}

app/views/pages/_subscriptions.html.haml
- content_for(:button_title, flush: true) do
  Subscriptions
  %small #{bill_period(:from)} - #{bill_period(:to)}

- content_for(:dropdown_amount, flush: true) do
  = currency(resource[:package][:total])

= render 'bill_section', id: 'subscription', target: 'subscriptions_expanded' do
  %table.table.subscriptions
    %caption This bill covers next months basic subscriptions
    - resource[:package][:subscriptions].each do |subscription|
      %tr
        %td.col-sm-3= subscription[:name]
        %td.col-sm-9
          .pull-right= currency(subscription[:cost])
    %tr
      %td
        %td
          %b.pull-right Subtotal #{currency(resource[:package][:total])}

app/views/pages/_tv_charges.html.haml
- content_for(:button_title, flush: true) do
  Sky TV Store
  %small.overview Rentals &amp; Purchases

- content_for(:dropdown_amount, flush: true) do
  = currency(rental_charge_total)

= render 'bill_section', id: 'tv_charges', target: 'tv_expanded' do
  %table.table.tv_charges
    %tr
      %th.col-sm-5 Title
      %th.col-sm-4
      %th.col-sm-3 Charge
    %caption Rentals &amp; Purchases
    - resource[:sky_store][:rentals].each do |rental|
      %tr
        %td.col-sm-5= rental[:title]
        %td.col-sm-4 Rental
        %td.col-sm-3= currency(rental[:cost])
    - resource[:sky_store][:buy_and_keep].each do |purchase|
      %tr
        %td.col-sm-5= purchase[:title]
        %td.col-sm-4 Purchase
        %td.col-sm-3.text-muted £0.00 (#{currency(purchase[:cost])} paid)
    %tr
      %td
      %td
      %td
        %b= currency(rental_charge_total)

app/views/pages/bill.html.haml
.col-sm-12
  - if resource.blank?
    - content_for :alert do
      .alert.alert-danger
        An error occurred whilst fetching your bill, please refresh the page to try again.
  - else
    %h3
      Latest Bill
      %small Due #{date_string(resource[:statement][:due])}
      %span.pull-right= currency(resource[:total])
    %hr

      = render 'subscriptions'
      %hr
      = render 'phone_charges'
      %hr
      = render 'tv_charges'
      %hr

      .pull-right
        = link_to bill_pdf_path, target: '_blank', class: 'btn' do
          %i.glyphicon.glyphicon-download
          %span Download PDF